[package]
name = "wayexpand-gui"
description = "Native Wayland graphical editor for WayExpand"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ab_glyph = "0.2.32"
anyhow.workspace = true
eframe = { version = "0.31.1", default-features = false, features = ["accesskit", "wayland", "default_fonts", "glow"] }
serde.workspace = true
serde_json.workspace = true
toml_edit = { version = "0.25.15", features = ["serde"] }
wayexpand-core = { path = "../core" }
wayexpand-backend-ibus = { path = "../backend-ibus" }
wayexpand-backend-input-method = { path = "../backend-input-method" }
wayexpand-backend-wlroots = { path = "../backend-wlroots" }
wayexpand-backend-kwin-window = { path = "../backend-kwin-window" }
