[package]
name = "wayexpand-backend-input-method"
description = "input-method-v2 source backend for WayExpand"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-misc.workspace = true
xkbcommon-rs = { workspace = true, features = ["server"] }
xkeysym = "0.2.1"
rustix = { version = "1", features = ["event"] }
unicode-segmentation.workspace = true
wayexpand-core = { path = "../core" }
