use crate::{
    config::capitalize_first_letter, render_template_with_cursor, CommandConfig,
    CommandEnvironment, Config, ConfigError, HotkeyConfig, KeyChord, MatchMode, Matcher,
    TextInjector,
};
#[cfg(unix)]
use std::os::fd::AsRawFd;
#[cfg(unix)]
use std::os::unix::process::CommandExt;
use std::{
    collections::VecDeque,
    io::Read,
    process::{Child, ChildStdout, Command, Stdio},
    sync::{
        atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering},
        mpsc, Arc,
    },
    thread::{self, JoinHandle},
    time::{Duration, Instant},
};

const MAX_RESULTS_PER_EVENT: usize = 1024;
const MAX_RESULT_BYTES_PER_EVENT: usize = 4 * 1024 * 1024;
const MAX_COMMAND_OUTPUT_BYTES: usize = 1024 * 1024;
const MINIMAL_COMMAND_PATH: &str = "/usr/local/bin:/usr/bin:/bin";
const ASYNC_COMMAND_QUEUE_CAPACITY: usize = 16;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputEvent {
    Text(String),
    /// A normalized key press. Backends should emit this before any text
    /// event generated by the same physical key.
    Key(KeyChord),
    Backspace,
    EndOfInput,
    Delimiter(char),
    Reset,
    /// Changes capture policy for the focused surface. Sensitive fields must
    /// disable matching and clear any text already buffered. This is a
    /// compositor/backend signal, not a user action (use `PauseChanged` for that).
    FocusChanged {
        sensitive: bool,
    },
    /// User-initiated pause/resume of text expansion. Independent from
    /// `FocusChanged`: both conditions disable capture when active.
    /// Resuming does not re-enable capture if still in a sensitive field.
    PauseChanged(bool),
    /// Reports which application is now focused, for `app_filter`-scoped
    /// expansions. `None` means unknown (no window tracker running, or the
    /// compositor does not support one) -- app-restricted expansions fail
    /// closed in that case rather than matching everywhere.
    WindowChanged(Option<WindowContext>),
}

/// The focused window's identity, as reported by a window tracker backend.
/// Both fields are best-effort and compositor-dependent: a toplevel may
/// expose an app id but not a title, or vice versa.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WindowContext {
    pub app_id: Option<String>,
    pub title: Option<String>,
}

#[derive(Debug, Clone, Default)]
struct NormalizedWindowContext {
    app_id: Option<String>,
    title: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExpansionResult {
    pub trigger: String,
    /// The exact characters that were matched in the input. This can differ
    /// from `trigger` when case propagation registered a Unicode case variant
    /// (for example, configured `ß` matched the typed text `SS`). Deletion
    /// must always use this value, never the configured trigger's length.
    pub matched_text: String,
    pub insert: String,
    /// Characters to move the cursor left after `insert` is typed, from a
    /// `{{cursor}}` marker in the replacement. `None`/`Some(0)` leave the
    /// cursor at the end, matching every replacement written before this
    /// existed.
    pub cursor_offset: Option<usize>,
    /// Character to preserve after the replacement. Evdev capture is
    /// non-exclusive, so the key that completes a word-boundary trigger or a
    /// trigger that is a prefix of another (e.g., `:a` vs `:address`) has
    /// already reached the app by the time the engine matches. Normally we
    /// delete it together with the trigger and append it to the replacement
    /// in one backend operation (`:sig ` becomes `signature `). This field is
    /// `None` for matches that complete immediately without a trailing key.
    pub reinsert_after: Option<char>,
    /// Explicit provenance: true if this expansion's replacement came from
    /// executing a command. Used for audit logging to distinguish command output
    /// from template-based expansions. No heuristics—this is set explicitly
    /// when the engine processes the command result.
    pub command_backed: bool,
    /// Whether this result is still immediately undoable. A deferred result
    /// can be completed after a later scalar from the same text event, which
    /// has the same undo invalidation semantics as immediate processing.
    pub undoable: bool,
}

/// Expansion result with deferred command execution.
/// Commands are not executed until caller approves via policy check.
#[derive(Debug, Clone)]
pub struct PendingExpansionResult {
    pub trigger: String,
    pub matched_text: String,
    pub template_text: String,
    pub cursor_offset: Option<usize>,
    pub reinsert_after: Option<char>,
    /// Organization-level output limit from the engine configuration (0 = unlimited).
    max_replacement_size: usize,
    config_index: usize,
    generation: u64,
    propagate_case: bool,
    cache_ms: u64,
    cached_output: Option<String>,
    undoable: bool,
    /// Command to execute (if any). Not yet executed; caller decides.
    pub command: Option<CommandConfig>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PendingExpansionDispatch {
    Ready(ExpansionResult),
    Queued,
}

/// Unified match plan: the result of successful matching before policy evaluation.
/// Contains all information needed to decide whether to execute and how to commit.
/// This structure has no side effects—it is read-only context for policy and execution.
#[derive(Debug, Clone)]
pub struct MatchPlan {
    // Matching result
    /// Exact matched text (may differ from trigger if case propagation registered variant)
    pub matched_text: String,
    pub terminating_char: Option<char>,
    pub cursor_offset: Option<usize>,

    // State snapshot at match time (used for policy decisions)
    pub generation: u64,
    pub sensitive_focus: bool,
    pub user_paused: bool,

    // Expansion details (cloned for lifetime independence)
    pub trigger_config: String,
    pub replacement_text: String,
    pub command: Option<Arc<CommandConfig>>,
    pub propagate_case: bool,
}

impl MatchPlan {
    pub fn is_command_backed(&self) -> bool {
        self.command.is_some()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HotkeyResult {
    pub chord: KeyChord,
    pub description: String,
    pub command: CommandConfig,
}

#[derive(Debug, thiserror::Error)]
pub enum ExpansionError {
    #[error("injection failed: {0}")]
    Injection(#[from] crate::InjectorError),
}

#[derive(Debug, thiserror::Error)]
pub enum HotkeyError {
    #[error("could not start hotkey action")]
    Spawn(#[source] std::io::Error),
    #[error("hotkey action timed out after {0} ms")]
    Timeout(u64),
    #[error("hotkey action failed with status {0}")]
    Failed(String),
    #[error("hotkey action queue is full")]
    QueueFull,
    #[error("hotkey action worker is unavailable")]
    WorkerUnavailable,
}

/// Runtime counters for command-backed expansions and hotkey actions.
/// Counters are monotonically increasing for the lifetime of an engine;
/// `command_queue_depth` is the current number of jobs waiting for the worker,
/// and `command_in_flight` is the number currently executing in worker threads.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct CommandMetrics {
    pub command_queue_depth: usize,
    pub command_in_flight: usize,
    pub command_queue_rejected_total: u64,
    pub command_timeout_total: u64,
    pub command_failure_total: u64,
}

pub struct ExpansionEngine {
    config: Config,
    /// Case-folded app filters are immutable for the lifetime of an engine;
    /// avoid allocating them on every candidate match.
    app_filters_lower: Vec<Vec<String>>,
    matcher: Matcher,
    matcher_indices: Vec<usize>,
    buffer: VecDeque<char>,
    max_buffer_chars: usize,
    /// Set whenever the buffer evicts a character from the front because it
    /// exceeded `max_buffer_chars`, and cleared only by `buffer.clear()`
    /// (a known boundary, e.g. after a match). Lets `match_allowed`
    /// distinguish "truly at the start of input" from "a preceding
    /// character existed but was evicted" -- the two cases an empty
    /// `rev().nth(length)` cannot tell apart on its own.
    buffer_truncated: bool,
    /// User-initiated pause state. Independent from sensitive field detection.
    user_paused: bool,
    /// Compositor/backend signal that focused field is sensitive (password,
    /// OTP, etc.). Independent from user_paused.
    sensitive_focus: bool,
    command_cache: Vec<Option<CommandCacheEntry>>,
    hotkeys: Vec<(KeyChord, usize)>,
    current_window: Option<WindowContext>,
    normalized_window: Option<NormalizedWindowContext>,
    undo_chord: Option<KeyChord>,
    /// The most recent successful expansion, kept only until the very next
    /// event of any other kind (see `process`): `(text to type back,
    /// exact text to erase)`. Not set for a result with a `{{cursor}}`
    /// marker, since undoing after the user has typed more text at that
    /// repositioned cursor has no single well-defined "erase N characters
    /// backward" meaning.
    last_expansion: Option<(String, String)>,
    /// Trigger text removed while a deferred result is being prepared. The
    /// reservation is released only after successful injection; otherwise it
    /// is restored before subsequent input is matched.
    deferred_matches: Vec<String>,
    input_generation: u64,
    async_commands: Option<AsyncCommandRuntime>,
    command_metrics: Arc<CommandMetricsState>,
    /// Whether a terminating character should be included in the replacement
    /// operation. Exclusive input sources have not delivered the delimiter to
    /// the application yet; non-exclusive sources such as evdev have.
    reinsert_terminators: bool,
}

#[derive(Debug, Clone)]
struct CommandCacheEntry {
    expires_at: Instant,
    value: String,
}

struct AsyncCommandRuntime {
    command_sender: mpsc::SyncSender<AsyncCommandJob>,
    hotkey_sender: mpsc::SyncSender<HotkeyResult>,
    receiver: mpsc::Receiver<AsyncCommandCompletion>,
    hotkey_receiver: mpsc::Receiver<AsyncHotkeyCompletion>,
    metrics: Arc<CommandMetricsState>,
    shutdown: Arc<AtomicBool>,
    command_worker: Option<JoinHandle<()>>,
    hotkey_worker: Option<JoinHandle<()>>,
}

/// Send a worker completion without making runtime shutdown dependent on a
/// receiver draining the old configuration's queue. Normal operation keeps
/// backpressure when the bounded completion channel is full; once shutdown is
/// requested, the completion can be discarded because the owning engine is
/// being replaced and must not wait indefinitely for stale output.
fn send_completion_or_shutdown<T>(
    sender: &mpsc::SyncSender<T>,
    mut completion: T,
    shutdown: &AtomicBool,
) -> bool {
    loop {
        if shutdown.load(Ordering::Acquire) {
            return false;
        }
        match sender.try_send(completion) {
            Ok(()) => return true,
            Err(mpsc::TrySendError::Disconnected(_)) => return false,
            Err(mpsc::TrySendError::Full(value)) => {
                completion = value;
                thread::sleep(Duration::from_millis(5));
            }
        }
    }
}

impl Drop for AsyncCommandRuntime {
    fn drop(&mut self) {
        // Stop accepting queued work and cancel any child currently running
        // on either worker before joining. Reloads happen on the daemon's
        // input loop, so waiting for an old command's normal timeout here
        // would briefly freeze capture and control handling.
        self.shutdown.store(true, Ordering::Release);
        if let Some(worker) = self.command_worker.take() {
            let _ = worker.join();
        }
        if let Some(worker) = self.hotkey_worker.take() {
            let _ = worker.join();
        }
    }
}

struct CommandMetricsState {
    queue_depth: AtomicUsize,
    in_flight: AtomicUsize,
    queue_rejected_total: AtomicU64,
    timeout_total: AtomicU64,
    failure_total: AtomicU64,
}

impl CommandMetricsState {
    fn new() -> Self {
        Self {
            queue_depth: AtomicUsize::new(0),
            in_flight: AtomicUsize::new(0),
            queue_rejected_total: AtomicU64::new(0),
            timeout_total: AtomicU64::new(0),
            failure_total: AtomicU64::new(0),
        }
    }

    fn snapshot(&self) -> CommandMetrics {
        CommandMetrics {
            command_queue_depth: self.queue_depth.load(Ordering::Relaxed),
            command_in_flight: self.in_flight.load(Ordering::Relaxed),
            command_queue_rejected_total: self.queue_rejected_total.load(Ordering::Relaxed),
            command_timeout_total: self.timeout_total.load(Ordering::Relaxed),
            command_failure_total: self.failure_total.load(Ordering::Relaxed),
        }
    }

    fn record_error(&self, timeout: bool) {
        if timeout {
            self.timeout_total.fetch_add(1, Ordering::Relaxed);
        } else {
            self.failure_total.fetch_add(1, Ordering::Relaxed);
        }
    }
}

impl AsyncCommandRuntime {
    fn try_send_command(&self, job: AsyncCommandJob) -> Result<(), QueueSendError> {
        self.try_send(&self.command_sender, job)
    }

    fn try_send_hotkey(&self, action: HotkeyResult) -> Result<(), QueueSendError> {
        self.try_send(&self.hotkey_sender, action)
    }

    fn try_send<T>(&self, sender: &mpsc::SyncSender<T>, job: T) -> Result<(), QueueSendError> {
        self.metrics.queue_depth.fetch_add(1, Ordering::Relaxed);
        match sender.try_send(job) {
            Ok(()) => Ok(()),
            Err(mpsc::TrySendError::Full(_)) => {
                self.metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                self.metrics
                    .queue_rejected_total
                    .fetch_add(1, Ordering::Relaxed);
                Err(QueueSendError::Full)
            }
            Err(mpsc::TrySendError::Disconnected(_)) => {
                self.metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                self.metrics
                    .queue_rejected_total
                    .fetch_add(1, Ordering::Relaxed);
                Err(QueueSendError::Disconnected)
            }
        }
    }
}

enum QueueSendError {
    Full,
    Disconnected,
}

enum AsyncCommandJob {
    Expansion {
        config_index: usize,
        generation: u64,
        additional_max_size: usize,
        command: CommandConfig,
        result: ExpansionResult,
    },
}

struct AsyncCommandCompletion {
    config_index: usize,
    generation: u64,
    cache_ms: u64,
    additional_max_size: usize,
    result: ExpansionResult,
    output: Result<String, CommandError>,
}

struct AsyncHotkeyCompletion {
    action: HotkeyResult,
    output: Result<(), HotkeyError>,
}

/// Return the exact erase/insert strings for an expansion transaction.
///
/// A non-exclusive word-boundary match has already delivered its terminating
/// character to the application. Since `apply` replaces that character along
/// with the trigger, undo must include it as well.
fn transaction_texts(
    restore: &str,
    replacement: &str,
    reinsert_after: Option<char>,
) -> (String, String) {
    let mut restore_text = restore.to_owned();
    let mut replacement_text = replacement.to_owned();
    if let Some(character) = reinsert_after {
        restore_text.push(character);
        replacement_text.push(character);
    }
    (restore_text, replacement_text)
}

impl ExpansionEngine {
    pub fn new(config: Config) -> Result<Self, ConfigError> {
        config.validate()?;
        // Triggers match literally (see `Matcher`, a case-sensitive char
        // trie), so a `propagate_case` expansion is matched by inserting
        // its uppercase and capitalized forms as additional trigger
        // strings mapped to the same config entry, rather than by making
        // matching itself case-insensitive (which would affect every
        // expansion, not just ones that opted in). `take_match` later reads
        // back which form was actually typed to decide how to case the
        // replacement. `effective_triggers()` is the single source of
        // truth for this expansion -- `validate()` (called just above)
        // checks collisions across the exact same variants, so a config
        // that reaches this point is already known not to have two
        // expansions competing for the same matcher entry.
        let enabled: Vec<(usize, String)> = config
            .expansion
            .iter()
            .enumerate()
            .filter(|(_, entry)| entry.enabled)
            .flat_map(|(index, entry)| {
                entry
                    .effective_triggers()
                    .into_iter()
                    .map(move |trigger| (index, trigger))
            })
            .collect();
        let matcher_indices = enabled.iter().map(|(index, _)| *index).collect();
        let matcher = Matcher::new(enabled.into_iter().map(|(_, trigger)| trigger));
        let app_filters_lower = config
            .expansion
            .iter()
            .map(|expansion| {
                expansion
                    .app_filter
                    .iter()
                    .map(|filter| filter.to_lowercase())
                    .collect()
            })
            .collect();
        let max_buffer_chars = config.settings.max_buffer_chars;
        // `validate()` above already confirmed this parses; a config that
        // fails to load is never used to construct an engine.
        let undo_chord = config
            .settings
            .undo_chord
            .as_deref()
            .and_then(|chord| KeyChord::parse(chord).ok());
        let command_cache = vec![None; config.expansion.len()];
        let hotkeys = config
            .hotkey
            .iter()
            .enumerate()
            .filter(|(_, binding)| binding.enabled)
            .filter_map(|(index, binding)| {
                KeyChord::parse(&binding.chord)
                    .ok()
                    .map(|chord| (chord, index))
            })
            .collect();
        Ok(Self {
            config,
            app_filters_lower,
            matcher,
            matcher_indices,
            buffer: VecDeque::new(),
            max_buffer_chars,
            buffer_truncated: false,
            user_paused: false,
            sensitive_focus: false,
            command_cache,
            hotkeys,
            current_window: None,
            normalized_window: None,
            undo_chord,
            last_expansion: None,
            deferred_matches: Vec::new(),
            input_generation: 0,
            async_commands: None,
            command_metrics: Arc::new(CommandMetricsState::new()),
            reinsert_terminators: true,
        })
    }

    /// Apply administrator-owned policy to an already constructed engine.
    /// This changes policy metadata only; matching state and runtime state are
    /// preserved.
    pub fn apply_administrator_policy(
        &mut self,
        policy: &crate::OrganizationPolicy,
    ) -> Result<(), ConfigError> {
        self.config.apply_administrator_policy(policy)
    }

    /// Configure whether delimiters reported with a match must be reinserted.
    /// Exclusive sources need this enabled; non-exclusive sources (evdev)
    /// should leave the physical delimiter to the focused application.
    pub fn set_reinsert_terminators(&mut self, enabled: bool) {
        self.reinsert_terminators = enabled;
    }

    pub fn reinserts_terminators(&self) -> bool {
        self.reinsert_terminators
    }

    /// Run command-backed expansions and hotkey actions on separate bounded
    /// worker queues. A slow expansion command cannot delay an urgent hotkey.
    /// This is enabled by the daemon; CLI and GUI previews remain synchronous
    /// so an explicit preview call can return its result directly.
    pub fn enable_async_commands(&mut self) -> bool {
        if self.async_commands.is_some() {
            return true;
        }
        let (command_sender, command_receiver) =
            mpsc::sync_channel::<AsyncCommandJob>(ASYNC_COMMAND_QUEUE_CAPACITY);
        let (hotkey_sender, hotkey_receiver) =
            mpsc::sync_channel::<HotkeyResult>(ASYNC_COMMAND_QUEUE_CAPACITY);
        let (completion_sender, completion_receiver) =
            mpsc::sync_channel(ASYNC_COMMAND_QUEUE_CAPACITY);
        let (hotkey_completion_sender, hotkey_completion_receiver) =
            mpsc::sync_channel(ASYNC_COMMAND_QUEUE_CAPACITY);
        let metrics = Arc::clone(&self.command_metrics);
        let shutdown = Arc::new(AtomicBool::new(false));
        let command_shutdown = Arc::clone(&shutdown);
        let worker_metrics = Arc::clone(&metrics);
        let command_worker = thread::Builder::new()
            .name("wayexpand-expansion-worker".into())
            .spawn(move || {
                while !command_shutdown.load(Ordering::Acquire) {
                    let job = match command_receiver.recv_timeout(Duration::from_millis(50)) {
                        Ok(job) => job,
                        Err(mpsc::RecvTimeoutError::Timeout) => continue,
                        Err(mpsc::RecvTimeoutError::Disconnected) => break,
                    };
                    // A runtime can be dropped during a configuration reload
                    // while work is still buffered in the channel. Do not
                    // start another external command after shutdown begins;
                    // only the command already executing at the boundary may
                    // finish under its existing timeout.
                    if command_shutdown.load(Ordering::Acquire) {
                        worker_metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                        break;
                    }
                    worker_metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                    worker_metrics.in_flight.fetch_add(1, Ordering::Relaxed);
                    let AsyncCommandJob::Expansion {
                        config_index,
                        generation,
                        additional_max_size,
                        command,
                        result,
                    } = job;
                    let cache_ms = command.cache_ms;
                    let output = run_command_with_shutdown(&command, Some(&command_shutdown));
                    worker_metrics.in_flight.fetch_sub(1, Ordering::Relaxed);
                    if let Err(error) = &output {
                        worker_metrics.record_error(matches!(error, CommandError::Timeout));
                    }
                    if !send_completion_or_shutdown(
                        &completion_sender,
                        AsyncCommandCompletion {
                            config_index,
                            generation,
                            cache_ms,
                            additional_max_size,
                            result,
                            output,
                        },
                        &command_shutdown,
                    ) {
                        break;
                    }
                }
            });
        let command_worker = match command_worker {
            Ok(worker) => worker,
            Err(_) => return false,
        };
        let hotkey_shutdown = Arc::clone(&shutdown);
        let hotkey_metrics = Arc::clone(&metrics);
        let hotkey_worker = thread::Builder::new()
            .name("wayexpand-hotkey-worker".into())
            .spawn(move || {
                while !hotkey_shutdown.load(Ordering::Acquire) {
                    let action = match hotkey_receiver.recv_timeout(Duration::from_millis(50)) {
                        Ok(action) => action,
                        Err(mpsc::RecvTimeoutError::Timeout) => continue,
                        Err(mpsc::RecvTimeoutError::Disconnected) => break,
                    };
                    // Match expansion workers: a hotkey still waiting in the
                    // old runtime must not acquire new side effects after a
                    // reload has requested shutdown.
                    if hotkey_shutdown.load(Ordering::Acquire) {
                        hotkey_metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                        break;
                    }
                    hotkey_metrics.queue_depth.fetch_sub(1, Ordering::Relaxed);
                    hotkey_metrics.in_flight.fetch_add(1, Ordering::Relaxed);
                    let output =
                        Self::execute_hotkey_with_shutdown(&action, Some(&hotkey_shutdown));
                    hotkey_metrics.in_flight.fetch_sub(1, Ordering::Relaxed);
                    if let Err(error) = &output {
                        hotkey_metrics.record_error(matches!(error, HotkeyError::Timeout(_)));
                    }
                    if !send_completion_or_shutdown(
                        &hotkey_completion_sender,
                        AsyncHotkeyCompletion { action, output },
                        &hotkey_shutdown,
                    ) {
                        break;
                    }
                }
            });
        if hotkey_worker.is_err() {
            // The command worker has already started, but async mode is not
            // usable without both workers. Close its queue and join it before
            // falling back, otherwise every partial startup leaks a thread
            // until the process exits (especially harmful during reloads or
            // under a tight systemd TasksMax).
            shutdown.store(true, Ordering::Release);
            drop(command_sender);
            let _ = command_worker.join();
            return false;
        }
        self.async_commands = Some(AsyncCommandRuntime {
            command_sender,
            hotkey_sender,
            receiver: completion_receiver,
            hotkey_receiver: hotkey_completion_receiver,
            metrics,
            shutdown,
            command_worker: Some(command_worker),
            hotkey_worker: Some(hotkey_worker.unwrap()),
        });
        true
    }

    pub fn async_commands_enabled(&self) -> bool {
        self.async_commands.is_some()
    }

    /// Snapshot command execution counters for diagnostics and status output.
    pub fn command_metrics(&self) -> CommandMetrics {
        self.command_metrics.snapshot()
    }

    /// Whether libei portal restoration tokens may be read and persisted.
    pub fn libei_token_persistence(&self) -> bool {
        self.config.settings.libei_token_persistence
    }

    /// Applies the administrator's command-execution decision before command
    /// jobs are queued. This is separate from the config-owned organization
    /// policy because the daemon also loads `/etc/wayexpand/policy.toml`.
    pub fn set_commands_disabled(&mut self, disabled: bool) {
        self.config.organization.disable_commands = disabled;
    }

    pub fn commands_disabled(&self) -> bool {
        self.config.organization.disable_commands
    }

    pub fn set_title_matching_disabled(&mut self, disabled: bool) {
        self.config.organization.disable_title_matching = disabled;
    }

    pub fn title_matching_disabled(&self) -> bool {
        self.config.organization.disable_title_matching
    }

    /// Return completed command expansions that are still safe to apply.
    /// Any intervening input, focus, pause, or window event advances the
    /// generation and causes late output to be discarded rather than erasing
    /// text at a cursor that may have moved.
    pub fn drain_completed_commands(&mut self) -> Vec<ExpansionResult> {
        let Some(runtime) = self.async_commands.as_ref() else {
            return Vec::new();
        };
        let completions: Vec<_> = runtime.receiver.try_iter().collect();
        let mut results = Vec::new();
        for completion in completions {
            let Ok(output) = completion.output else {
                continue;
            };

            // Reconstruct MatchPlan context from completion for postflight checks
            let plan = MatchPlan {
                matched_text: completion.result.matched_text.clone(),
                terminating_char: completion.result.reinsert_after,
                cursor_offset: completion.result.cursor_offset,
                generation: completion.generation,
                sensitive_focus: false, // snapshot from queue time (conservative)
                user_paused: false,     // snapshot from queue time (conservative)
                trigger_config: self.config.expansion[completion.config_index]
                    .trigger
                    .clone(),
                replacement_text: self.config.expansion[completion.config_index]
                    .replacement
                    .clone(),
                command: self.config.expansion[completion.config_index]
                    .command
                    .as_ref()
                    .map(|c| Arc::new(c.clone())),
                propagate_case: self.config.expansion[completion.config_index].propagate_case,
            };

            // Apply postflight policy: check generation, output size, state changes
            let Some(validated_output) = self.apply_postflight_policy(&plan, &output) else {
                self.restore_deferred_match(&completion.result.matched_text);
                continue;
            };
            if completion.additional_max_size > 0
                && validated_output.len() > completion.additional_max_size
            {
                self.restore_deferred_match(&completion.result.matched_text);
                continue;
            }

            // Update cache before case propagation (cache stores original command output)
            if completion.cache_ms > 0 {
                self.command_cache[completion.config_index] = Some(CommandCacheEntry {
                    expires_at: Instant::now() + Duration::from_millis(completion.cache_ms),
                    value: validated_output.clone(),
                });
            }

            // Apply case propagation
            let final_output = if plan.propagate_case {
                apply_case_style(&plan.matched_text, &validated_output)
            } else {
                validated_output
            };

            // Build final result
            let mut result = completion.result;
            result.insert = final_output;
            results.push(result);
        }
        results
    }

    /// Complete a deferred match after caller-side preflight policy approval.
    /// Cache and case state are prepared here; undo state is committed only
    /// after the caller successfully injects the returned result.
    /// `additional_max_size` is a separately loaded administrator limit;
    /// zero means that only the limit carried by the engine is applied.
    fn execute_pending_inline(
        &mut self,
        pending: PendingExpansionResult,
        additional_max_size: usize,
    ) -> Result<ExpansionResult, CommandError> {
        // Static results are completed immediately after their input event has
        // been parsed, so a later scalar in that same event may have advanced
        // the per-scalar generation. Command-backed results must still match
        // the current generation because they can complete asynchronously.
        if (pending.command.is_some() && pending.generation != self.input_generation)
            || self.user_paused
            || self.sensitive_focus
        {
            return Err(CommandError::StaleInput);
        }
        if pending.command.is_some() && self.config.organization.disable_commands {
            return Err(CommandError::PolicyBlocked);
        }

        let command_backed = pending.command.is_some();
        let output = if let Some(cached) = pending.cached_output {
            cached
        } else if let Some(command) = &pending.command {
            run_command(command)?
        } else {
            pending.template_text
        };

        for limit in [pending.max_replacement_size, additional_max_size] {
            if limit > 0 && output.len() > limit {
                return Err(CommandError::PolicyOutputTooLarge {
                    size: output.len(),
                    limit,
                });
            }
        }

        if command_backed && pending.cache_ms > 0 {
            self.command_cache[pending.config_index] = Some(CommandCacheEntry {
                expires_at: Instant::now() + Duration::from_millis(pending.cache_ms),
                value: output.clone(),
            });
        }

        let insert = if pending.propagate_case {
            apply_case_style(&pending.matched_text, &output)
        } else {
            output
        };
        Ok(ExpansionResult {
            trigger: pending.trigger,
            matched_text: pending.matched_text,
            insert,
            cursor_offset: pending.cursor_offset,
            reinsert_after: pending.reinsert_after,
            command_backed,
            undoable: pending.undoable,
        })
    }

    /// Complete static/cache-hit matches immediately and queue uncached
    /// commands on the bounded expansion worker. Command execution never
    /// falls back to the caller thread when workers are unavailable.
    pub fn dispatch_pending_with_policy(
        &mut self,
        pending: PendingExpansionResult,
        additional_max_size: usize,
    ) -> Result<PendingExpansionDispatch, CommandError> {
        let matched_text = pending.matched_text.clone();
        if (pending.command.is_some() && pending.generation != self.input_generation)
            || self.user_paused
            || self.sensitive_focus
        {
            self.restore_deferred_match(&matched_text);
            return Err(CommandError::StaleInput);
        }
        if pending.command.is_some() && self.config.organization.disable_commands {
            self.restore_deferred_match(&matched_text);
            return Err(CommandError::PolicyBlocked);
        }

        let Some(command) = pending.command.as_ref() else {
            return match self.execute_pending_inline(pending, additional_max_size) {
                Ok(result) => Ok(PendingExpansionDispatch::Ready(result)),
                Err(error) => {
                    self.restore_deferred_match(&matched_text);
                    Err(error)
                }
            };
        };
        if pending.cached_output.is_some() {
            return match self.execute_pending_inline(pending, additional_max_size) {
                Ok(result) => Ok(PendingExpansionDispatch::Ready(result)),
                Err(error) => {
                    self.restore_deferred_match(&matched_text);
                    Err(error)
                }
            };
        }

        let Some(runtime) = self.async_commands.as_ref() else {
            self.restore_deferred_match(&matched_text);
            return Err(CommandError::WorkerUnavailable);
        };
        let result = ExpansionResult {
            trigger: pending.trigger,
            matched_text: pending.matched_text,
            insert: String::new(),
            cursor_offset: pending.cursor_offset,
            reinsert_after: pending.reinsert_after,
            command_backed: true,
            undoable: pending.undoable,
        };
        let job = AsyncCommandJob::Expansion {
            config_index: pending.config_index,
            generation: pending.generation,
            additional_max_size,
            command: command.clone(),
            result,
        };
        if let Err(error) = runtime.try_send_command(job) {
            self.restore_deferred_match(&matched_text);
            return Err(match error {
                QueueSendError::Full => CommandError::QueueFull,
                QueueSendError::Disconnected => CommandError::WorkerUnavailable,
            });
        }
        Ok(PendingExpansionDispatch::Queued)
    }

    /// Commit undo state after an expansion result was successfully injected.
    /// Deferred callers must not record undo state before their own safety and
    /// output checks have completed.
    pub fn commit_applied_expansion(&mut self, result: &ExpansionResult) {
        self.release_deferred_match_for_result(result);
        if result.undoable && result.cursor_offset.is_none() {
            self.last_expansion = Some(transaction_texts(
                &result.matched_text,
                &result.insert,
                result.reinsert_after,
            ));
        }
    }

    /// Restore a deferred trigger when its result will not be injected. The
    /// trigger is put back before any later input so matcher order remains the
    /// same as the non-exclusive application's input stream.
    pub fn restore_deferred_match(&mut self, matched_text: &str) {
        if self.take_deferred_reservation(matched_text).is_some() {
            self.buffer.extend(matched_text.chars());
        }
    }

    /// Remove the reservation represented by a result. Evdev may absorb one
    /// delimiter into `matched_text` after the reservation was created, so a
    /// result can be the reserved trigger plus exactly one scalar.
    fn take_deferred_reservation(&mut self, matched_text: &str) -> Option<String> {
        let index = self.deferred_matches.iter().position(|reserved| {
            reserved == matched_text
                || matched_text
                    .strip_prefix(reserved)
                    .is_some_and(|suffix| suffix.chars().count() == 1)
        })?;
        Some(self.deferred_matches.remove(index))
    }

    fn release_deferred_match_for_result(&mut self, result: &ExpansionResult) {
        self.take_deferred_reservation(&result.matched_text);
    }

    fn restore_deferred_matches(&mut self) {
        let reservations = std::mem::take(&mut self.deferred_matches);
        for matched_text in reservations {
            self.buffer.extend(matched_text.chars());
        }
    }

    /// Queue a hotkey action for bounded asynchronous execution. The caller
    /// must drain completions periodically; neither enqueueing nor draining
    /// waits for the child process.
    pub fn queue_hotkey(&self, action: &HotkeyResult) -> Result<(), HotkeyError> {
        let Some(runtime) = self.async_commands.as_ref() else {
            return Err(HotkeyError::WorkerUnavailable);
        };
        runtime
            .try_send_hotkey(action.clone())
            .map_err(|error| match error {
                QueueSendError::Full => HotkeyError::QueueFull,
                QueueSendError::Disconnected => HotkeyError::WorkerUnavailable,
            })
    }

    /// Return hotkey action completions without waiting for any child
    /// process. Results are intended for logging and operational status; the
    /// action itself has already completed on the worker thread.
    pub fn drain_completed_hotkeys(&mut self) -> Vec<(HotkeyResult, Result<(), HotkeyError>)> {
        let Some(runtime) = self.async_commands.as_ref() else {
            return Vec::new();
        };
        runtime
            .hotkey_receiver
            .try_iter()
            .map(|completion| (completion.action, completion.output))
            .collect()
    }

    /// The currently known focused window, if any. Used to carry window
    /// context across a config reload: reload replaces the whole engine
    /// (parse-then-swap), which would otherwise silently forget the last
    /// known window until the next real focus change -- wrongly
    /// fail-closing `app_filter`-scoped expansions for a window the user
    /// never actually left.
    pub fn current_window(&self) -> Option<&WindowContext> {
        self.current_window.as_ref()
    }

    /// Restores window context captured via `current_window` before this
    /// engine replaced a previous one. Does not clear the match buffer,
    /// matching `InputEvent::WindowChanged`'s own behavior (see its
    /// handler for why that clear is unnecessary).
    pub fn set_current_window(&mut self, window: Option<WindowContext>) {
        self.set_window_context(window);
    }

    fn set_window_context(&mut self, window: Option<WindowContext>) {
        self.normalized_window = window.as_ref().map(|window| NormalizedWindowContext {
            app_id: window.app_id.as_ref().map(|value| value.to_lowercase()),
            title: window.title.as_ref().map(|value| value.to_lowercase()),
        });
        self.current_window = window;
    }

    /// Returns whether the user has manually paused text expansion.
    /// This must be preserved across config reloads to maintain pause state.
    pub fn is_user_paused(&self) -> bool {
        self.user_paused
    }

    /// Restores user pause state from a previous engine instance.
    /// Critical for config reloads to preserve pause state.
    pub fn set_user_paused(&mut self, paused: bool) {
        self.user_paused = paused;
    }

    /// Returns whether the focused field is sensitive (password, OTP, etc).
    /// This must be preserved across config reloads to maintain input protection.
    pub fn is_sensitive_focus(&self) -> bool {
        self.sensitive_focus
    }

    /// Restores sensitive field focus state from a previous engine instance.
    /// Critical for config reloads to preserve password-field protection.
    pub fn set_sensitive_focus(&mut self, sensitive: bool) {
        self.sensitive_focus = sensitive;
    }

    /// Whether text expansion capture is currently enabled.
    /// Both user pause and sensitive field focus independently disable capture.
    fn is_capture_enabled(&self) -> bool {
        !self.user_paused && !self.sensitive_focus
    }

    /// Resolve a normalized key chord into configured actions. This method is
    /// side-effect free; the daemon or script runtime owns execution policy,
    /// cancellation, and capability checks.
    /// Invalidate pending asynchronous expansions by incrementing the generation
    /// counter. Called when any key event arrives, before processing the hotkey
    /// action. This ensures running commands are discarded when the user presses
    /// another key, preventing output injection at the wrong cursor position.
    ///
    /// Note: does not clear `last_expansion` (the undo transaction) because
    /// the undo chord itself arrives as a Key event, and clearing it would make
    /// undo impossible to trigger.
    pub fn note_key_event(&mut self) {
        self.input_generation = self.input_generation.wrapping_add(1);
    }

    pub fn process_key(&self, chord: &KeyChord) -> Vec<HotkeyResult> {
        if !self.is_capture_enabled() {
            return Vec::new();
        }
        self.hotkeys
            .iter()
            .filter(|(configured, _)| configured.matches(chord))
            .filter_map(|(_, index)| {
                let binding: &HotkeyConfig = self.config.hotkey.get(*index)?;
                Some(HotkeyResult {
                    chord: chord.clone(),
                    description: binding.description.clone(),
                    command: binding.command.clone(),
                })
            })
            .collect()
    }

    /// Prepare the `ExpansionResult` that would undo the most recent
    /// expansion without consuming its undo record. The caller must call
    /// [`Self::commit_undo`] only after the result has been injected.
    pub fn prepare_undo(&self, chord: &KeyChord) -> Option<ExpansionResult> {
        if !self.is_capture_enabled() {
            return None;
        }
        if !self.undo_chord.as_ref()?.matches(chord) {
            return None;
        }
        let (restore_text, erase_text) = self.last_expansion.as_ref()?;
        Some(ExpansionResult {
            trigger: String::new(),
            matched_text: erase_text.clone(),
            insert: restore_text.clone(),
            cursor_offset: None,
            reinsert_after: None,
            command_backed: false,
            undoable: false,
        })
    }

    /// Commit a previously prepared undo after successful injection.
    /// A mismatched result is ignored so a stale failure cannot consume a
    /// newer undo record.
    pub fn commit_undo(&mut self, result: &ExpansionResult) {
        if self
            .last_expansion
            .as_ref()
            .is_some_and(|(restore, erase)| {
                restore == &result.insert && erase == &result.matched_text
            })
        {
            self.last_expansion = None;
        }
    }

    /// If `chord` matches the configured `settings.undo_chord` and an
    /// undoable expansion is still pending, consumes it and returns the
    /// `ExpansionResult` that reverts it. This convenience method is kept for
    /// callers that apply the result synchronously; daemon code should use
    /// [`Self::prepare_undo`] and [`Self::commit_undo`] around injection.
    pub fn try_undo(&mut self, chord: &KeyChord) -> Option<ExpansionResult> {
        let result = self.prepare_undo(chord)?;
        self.commit_undo(&result);
        Some(result)
    }

    /// Execute one validated hotkey action without invoking a shell. Output
    /// is discarded and the process is bounded by the configured timeout.
    /// This is intentionally synchronous for explicit, user-initiated
    /// callers; the daemon must use [`Self::queue_hotkey`] so its capture loop
    /// never waits for a child process.
    pub fn execute_hotkey(result: &HotkeyResult) -> Result<(), HotkeyError> {
        Self::execute_hotkey_with_shutdown(result, None)
    }

    fn execute_hotkey_with_shutdown(
        result: &HotkeyResult,
        shutdown: Option<&AtomicBool>,
    ) -> Result<(), HotkeyError> {
        let mut command = Command::new(&result.command.program);
        configure_command_environment(&mut command, &result.command);
        command
            .args(&result.command.args)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null());
        configure_process_group(&mut command);
        let mut child = command.spawn().map_err(HotkeyError::Spawn)?;
        let deadline = Instant::now() + Duration::from_millis(result.command.timeout_ms);
        let status = loop {
            if shutdown.is_some_and(|flag| flag.load(Ordering::Acquire)) {
                kill_process_group(&child);
                let _ = child.wait();
                return Err(HotkeyError::Timeout(result.command.timeout_ms));
            }
            match child.try_wait() {
                Ok(Some(status)) => break status,
                Ok(None) if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
                Ok(None) => {
                    kill_process_group(&child);
                    let _ = child.wait();
                    return Err(HotkeyError::Timeout(result.command.timeout_ms));
                }
                Err(error) => {
                    kill_process_group(&child);
                    let _ = child.wait();
                    return Err(HotkeyError::Spawn(error));
                }
            }
        };

        // Best-effort cleanup for ordinary descendants; direct commands are
        // trusted executable content, not a service/cgroup containment model.
        kill_process_group(&child);

        if status.success() {
            Ok(())
        } else {
            Err(HotkeyError::Failed(status.to_string()))
        }
    }

    /// Process an event stream. A text event may contain multiple Unicode
    /// scalar values; matching is performed after each one.
    pub fn process(&mut self, event: InputEvent) -> Vec<ExpansionResult> {
        // A pending undo is valid only immediately after the expansion it
        // would revert, with no other event in between. `InputEvent::Key`
        // is exempt: it never touches the buffer or produces a result here
        // (see below), and is how the undo chord itself arrives -- clearing
        // on it would make undo impossible to ever trigger.
        if !matches!(event, InputEvent::Key(_)) {
            self.last_expansion = None;
        }
        match event {
            InputEvent::Key(_) => {
                self.note_key_event();
                Vec::new()
            }
            InputEvent::Text(text) => {
                let mut results = Vec::new();
                let mut result_bytes = 0usize;
                if !self.is_capture_enabled() {
                    return results;
                }
                for character in text.chars() {
                    // An undoable expansion is valid only when no later
                    // scalar from this same text event follows it.
                    if !results.is_empty() {
                        self.last_expansion = None;
                    }
                    self.input_generation = self.input_generation.wrapping_add(1);
                    let pending = self.matcher.find_suffix(self.buffer.iter().rev().copied());
                    if let Some((index, length)) = pending {
                        if let Some(config_index) = self.matcher_indices.get(index).copied() {
                            let match_mode = self.config.expansion[config_index].match_mode;
                            // `trigger` is the configured lowercase form.
                            // With propagate_case, the pending suffix may
                            // instead be `:A` or `:AB`; continuation must be
                            // checked against the text the user actually
                            // typed, not the generated trie sibling.
                            let typed: String = {
                                let start = self.buffer.len().saturating_sub(length);
                                self.buffer.iter().skip(start).collect()
                            };
                            if !self.matcher.can_continue(&typed, character) {
                                let trailing_word_character = match_mode == MatchMode::WordBoundary
                                    && is_word_character(character);
                                if !trailing_word_character {
                                    if let Some(result) =
                                        self.take_match(config_index, length, Some(character))
                                    {
                                        let bytes = result
                                            .trigger
                                            .len()
                                            .saturating_add(result.insert.len());
                                        if results.len() >= MAX_RESULTS_PER_EVENT
                                            || result_bytes.saturating_add(bytes)
                                                > MAX_RESULT_BYTES_PER_EVENT
                                        {
                                            self.clear_buffer();
                                            break;
                                        }
                                        result_bytes = result_bytes.saturating_add(bytes);
                                        results.push(result);
                                    }
                                }
                            }
                        }
                    }
                    if results.len() >= MAX_RESULTS_PER_EVENT {
                        self.clear_buffer();
                        break;
                    }
                    self.buffer.push_back(character);
                    while self.buffer.len() > self.max_buffer_chars {
                        self.buffer.pop_front();
                        self.buffer_truncated = true;
                    }
                    if let Some((index, length)) =
                        self.matcher.find_suffix(self.buffer.iter().rev().copied())
                    {
                        let config_index = self.matcher_indices.get(index).copied();
                        let Some(config_index) = config_index else {
                            self.clear_buffer();
                            continue;
                        };
                        let (trigger, match_mode) = {
                            let expansion = &self.config.expansion[config_index];
                            (expansion.trigger.clone(), expansion.match_mode)
                        };
                        // The actually-typed suffix, which may be an
                        // uppercase or capitalized variant of `trigger` for
                        // a `propagate_case` expansion (see
                        // `ExpansionEngine::new`): `has_continuation` must
                        // be checked against what was typed, since that is
                        // the string actually present in the forward trie,
                        // not necessarily `trigger` itself.
                        let typed: String = {
                            let start = self.buffer.len().saturating_sub(length);
                            self.buffer.iter().skip(start).collect()
                        };
                        if self.matcher.has_continuation(&typed)
                            || match_mode == MatchMode::WordBoundary
                        {
                            continue;
                        }
                        if let Some(result) = self.take_match(config_index, length, None) {
                            let expansion_bytes = trigger.len().saturating_add(result.insert.len());
                            if result_bytes.saturating_add(expansion_bytes)
                                > MAX_RESULT_BYTES_PER_EVENT
                            {
                                self.clear_buffer();
                                break;
                            }
                            result_bytes = result_bytes.saturating_add(expansion_bytes);
                            results.push(result);
                        }
                        // Do not allow a replacement to combine with the
                        // next typed text and accidentally trigger again.
                        self.clear_buffer();
                    }
                }
                results
            }
            InputEvent::Delimiter(character) => {
                self.process(InputEvent::Text(character.to_string()))
            }
            InputEvent::Backspace => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.buffer.pop_back();
                Vec::new()
            }
            InputEvent::EndOfInput => {
                self.input_generation = self.input_generation.wrapping_add(1);
                let result = self
                    .matcher
                    .find_suffix(self.buffer.iter().rev().copied())
                    .and_then(|(index, length)| {
                        self.matcher_indices
                            .get(index)
                            .copied()
                            .and_then(|config_index| self.take_match(config_index, length, None))
                    });
                self.clear_buffer();
                result.into_iter().collect()
            }
            InputEvent::Reset => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::FocusChanged { sensitive } => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.sensitive_focus = sensitive;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::PauseChanged(paused) => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.user_paused = paused;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::WindowChanged(window) => {
                self.input_generation = self.input_generation.wrapping_add(1);
                // The text in the buffer belongs to the previously-focused
                // application. Text expansion state must be scoped to the
                // focused window, not to the desktop session. Even if
                // app_filter would correctly re-evaluate against the new
                // window, the physical characters in the buffer are from the
                // old application and must not be used to compute replacements
                // for the new one. This prevents cross-window trigger matches
                // that can cause unrelated text deletion.
                self.set_window_context(window);
                self.clear_buffer();
                Vec::new()
            }
        }
    }

    /// Process input and return pending expansion results for deferred execution.
    /// Commands are NOT executed; caller must check policy and complete results
    /// with `dispatch_pending_with_policy()` to preserve engine state.
    pub fn process_deferred(&mut self, event: InputEvent) -> Vec<PendingExpansionResult> {
        self.restore_deferred_matches();
        if !matches!(event, InputEvent::Key(_)) {
            self.last_expansion = None;
        }
        match event {
            InputEvent::Key(_) => {
                self.note_key_event();
                Vec::new()
            }
            InputEvent::Text(text) => {
                let mut results = Vec::new();
                let mut result_bytes = 0usize;
                if !self.is_capture_enabled() {
                    return results;
                }
                for character in text.chars() {
                    // Match the immediate processor's undo semantics: once
                    // another scalar follows a match in the same event, that
                    // earlier expansion is no longer immediately undoable.
                    if !results.is_empty() {
                        for result in &mut results {
                            result.undoable = false;
                        }
                    }
                    self.input_generation = self.input_generation.wrapping_add(1);
                    let pending = self.matcher.find_suffix(self.buffer.iter().rev().copied());
                    if let Some((index, length)) = pending {
                        if let Some(config_index) = self.matcher_indices.get(index).copied() {
                            let match_mode = self.config.expansion[config_index].match_mode;
                            let typed: String = {
                                let start = self.buffer.len().saturating_sub(length);
                                self.buffer.iter().skip(start).collect()
                            };
                            if !self.matcher.can_continue(&typed, character) {
                                let trailing_word_character = match_mode == MatchMode::WordBoundary
                                    && is_word_character(character);
                                if !trailing_word_character {
                                    if let Some(result) = self.take_match_deferred(
                                        config_index,
                                        length,
                                        Some(character),
                                    ) {
                                        let bytes = result
                                            .trigger
                                            .len()
                                            .saturating_add(result.template_text.len());
                                        if results.len() >= MAX_RESULTS_PER_EVENT
                                            || result_bytes.saturating_add(bytes)
                                                > MAX_RESULT_BYTES_PER_EVENT
                                        {
                                            self.clear_buffer();
                                            break;
                                        }
                                        result_bytes = result_bytes.saturating_add(bytes);
                                        results.push(result);
                                    }
                                }
                            }
                        }
                    }
                    if results.len() >= MAX_RESULTS_PER_EVENT {
                        self.clear_buffer();
                        break;
                    }
                    self.buffer.push_back(character);
                    while self.buffer.len() > self.max_buffer_chars {
                        self.buffer.pop_front();
                        self.buffer_truncated = true;
                    }
                    if let Some((index, length)) =
                        self.matcher.find_suffix(self.buffer.iter().rev().copied())
                    {
                        let config_index = self.matcher_indices.get(index).copied();
                        let Some(config_index) = config_index else {
                            self.clear_buffer();
                            continue;
                        };
                        let (trigger, match_mode) = {
                            let expansion = &self.config.expansion[config_index];
                            (expansion.trigger.clone(), expansion.match_mode)
                        };
                        let typed: String = {
                            let start = self.buffer.len().saturating_sub(length);
                            self.buffer.iter().skip(start).collect()
                        };
                        if self.matcher.has_continuation(&typed)
                            || match_mode == MatchMode::WordBoundary
                        {
                            continue;
                        }
                        if let Some(result) = self.take_match_deferred(config_index, length, None) {
                            let expansion_bytes =
                                trigger.len().saturating_add(result.template_text.len());
                            if result_bytes.saturating_add(expansion_bytes)
                                > MAX_RESULT_BYTES_PER_EVENT
                            {
                                self.clear_buffer();
                                break;
                            }
                            result_bytes = result_bytes.saturating_add(expansion_bytes);
                            results.push(result);
                        }
                        self.clear_buffer();
                    }
                }
                results
            }
            InputEvent::Delimiter(character) => {
                self.process_deferred(InputEvent::Text(character.to_string()))
            }
            InputEvent::Backspace => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.buffer.pop_back();
                Vec::new()
            }
            InputEvent::EndOfInput => {
                self.input_generation = self.input_generation.wrapping_add(1);
                let result = self
                    .matcher
                    .find_suffix(self.buffer.iter().rev().copied())
                    .and_then(|(index, length)| {
                        self.matcher_indices
                            .get(index)
                            .copied()
                            .and_then(|config_index| {
                                self.take_match_deferred(config_index, length, None)
                            })
                    });
                self.clear_buffer();
                result
                    .map(|mut pending| {
                        pending.generation = self.input_generation;
                        pending
                    })
                    .into_iter()
                    .collect()
            }
            InputEvent::Reset => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::FocusChanged { sensitive } => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.sensitive_focus = sensitive;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::PauseChanged(paused) => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.user_paused = paused;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::WindowChanged(window) => {
                self.input_generation = self.input_generation.wrapping_add(1);
                self.set_window_context(window);
                self.clear_buffer();
                Vec::new()
            }
        }
    }

    /// Apply preflight policy to a match plan. Decides if execution is allowed before any side effects.
    /// Returns the plan if approved, None if blocked by policy.
    fn apply_preflight_policy(&self, plan: MatchPlan) -> Option<MatchPlan> {
        // Commands are disabled by policy
        if plan.is_command_backed() && self.config.organization.disable_commands {
            return None;
        }

        // User has paused expansion
        if self.user_paused {
            return None;
        }

        // Sensitive focus (password field, etc.) disables expansion
        if self.sensitive_focus {
            return None;
        }

        Some(plan)
    }

    /// Apply postflight policy to command output. Validates output before injection.
    /// Called after command execution completes, before result is committed.
    /// Returns output if allowed, None if validation fails.
    fn apply_postflight_policy(&self, plan: &MatchPlan, output: &str) -> Option<String> {
        // Check max replacement size policy (0 = no limit)
        let max_size = self.config.organization.max_replacement_size;
        if max_size > 0 && output.len() > max_size {
            return None;
        }

        // Generation changed between match time and command completion
        // This means other input events occurred; result might be stale
        if plan.generation != self.input_generation {
            return None;
        }

        // State changed between match and completion - user paused or focused sensitive field
        if plan.sensitive_focus != self.sensitive_focus || plan.user_paused != self.user_paused {
            return None;
        }

        Some(output.to_string())
    }

    /// Unified commit: apply all post-execution logic to create final ExpansionResult.
    /// This is the single path for committing any expansion (static or command-backed).
    /// Handles case propagation, undo state, and result metadata.
    fn commit_expansion(&mut self, plan: &MatchPlan, insert: String) -> ExpansionResult {
        let mut final_insert = insert;

        // Apply case propagation if configured (applies to all expansion types)
        if plan.propagate_case {
            final_insert = apply_case_style(&plan.matched_text, &final_insert);
        }

        let reinsert_after = plan.terminating_char.filter(|_| self.reinsert_terminators);

        // Save undo state (only if no cursor offset - cursor marker expansions don't support undo)
        // Skip undo for async commands since they return empty immediately
        if plan.cursor_offset.is_none()
            && (!plan.is_command_backed() || self.async_commands.is_none())
        {
            self.last_expansion = Some(transaction_texts(
                &plan.matched_text,
                &final_insert,
                reinsert_after,
            ));
        }

        ExpansionResult {
            trigger: plan.trigger_config.clone(),
            matched_text: plan.matched_text.clone(),
            insert: final_insert,
            cursor_offset: plan.cursor_offset,
            reinsert_after,
            command_backed: plan.is_command_backed(),
            undoable: true,
        }
    }

    /// Create a match plan without side effects. Returns context for policy evaluation and execution.
    /// This is the unified matching path for both immediate and deferred execution.
    fn take_match_plan(
        &self,
        config_index: usize,
        length: usize,
        terminating_char: Option<char>,
    ) -> Option<MatchPlan> {
        if !self.match_allowed(config_index, length) {
            return None;
        }

        let expansion = &self.config.expansion[config_index];
        let propagate_case = expansion.propagate_case;

        // Read the actually-typed trigger text (may be case variant due to case propagation)
        let matched_text: String = {
            let start = self.buffer.len().saturating_sub(length);
            self.buffer.iter().skip(start).collect()
        };

        // Render static templates once at match time. The rendered text and
        // cursor offset must come from the same context (and are reused by
        // both immediate and deferred paths); commands are rendered later.
        let (replacement_text, cursor_offset) = if expansion.command.is_some() {
            (expansion.replacement.clone(), None)
        } else {
            let (rendered, cursor_offset) = render_template_with_cursor(
                &expansion.replacement,
                &crate::TemplateContext::system(),
            )
            .ok()?;
            (rendered, cursor_offset)
        };

        Some(MatchPlan {
            matched_text,
            terminating_char,
            cursor_offset,
            generation: self.input_generation,
            sensitive_focus: self.sensitive_focus,
            user_paused: self.user_paused,
            trigger_config: expansion.trigger.clone(),
            replacement_text,
            command: expansion.command.as_ref().map(|c| Arc::new(c.clone())),
            propagate_case,
        })
    }

    fn take_match(
        &mut self,
        config_index: usize,
        length: usize,
        terminating_char: Option<char>,
    ) -> Option<ExpansionResult> {
        // Generate match plan with full context
        let plan = self.take_match_plan(config_index, length, terminating_char)?;

        // Apply preflight policy
        self.apply_preflight_policy(plan.clone())?;

        let expansion = &self.config.expansion[config_index];

        // Check cache before deciding on async vs sync
        let cached_command = expansion.command.as_ref().and_then(|command| {
            (command.cache_ms > 0)
                .then(|| self.command_cache[config_index].as_ref())
                .flatten()
                .filter(|entry| entry.expires_at > Instant::now())
                .map(|entry| entry.value.clone())
        });

        // Cached command: use cache
        if let Some(cached_value) = cached_command {
            for _ in 0..length {
                self.buffer.pop_back();
            }
            // Commit with cached value (already cached, no re-caching needed)
            return Some(self.commit_expansion(&plan, cached_value));
        }

        // Async command: queue and return empty
        if let Some(runtime) = self.async_commands.as_ref() {
            if expansion.command.is_some() {
                let result = ExpansionResult {
                    trigger: plan.trigger_config.clone(),
                    matched_text: plan.matched_text.clone(),
                    insert: String::new(),
                    cursor_offset: None,
                    reinsert_after: plan.terminating_char.filter(|_| self.reinsert_terminators),
                    command_backed: true,
                    undoable: true,
                };
                let job = AsyncCommandJob::Expansion {
                    config_index,
                    generation: self.input_generation,
                    additional_max_size: 0,
                    command: expansion.command.clone().unwrap(),
                    result,
                };
                if runtime.try_send_command(job).is_err() {
                    return None;
                }
                // Do not consume the trigger until the worker has accepted
                for _ in 0..length {
                    self.buffer.pop_back();
                }
                self.last_expansion = None;
                return None;
            }
        }

        // Sync fallback: static templates were rendered as part of the plan;
        // command output still executes here (or uses its cache above).
        let insert = if expansion.command.is_some() {
            self.render_expansion(config_index).ok()?
        } else {
            plan.replacement_text.clone()
        };
        for _ in 0..length {
            self.buffer.pop_back();
        }
        Some(self.commit_expansion(&plan, insert))
    }

    /// Deferred execution variant: returns pending results without executing commands.
    /// Caller must check policy and complete through the
    /// engine so cache and case propagation are prepared. Undo state is
    /// committed by the caller only after successful injection.
    fn take_match_deferred(
        &mut self,
        config_index: usize,
        length: usize,
        terminating_char: Option<char>,
    ) -> Option<PendingExpansionResult> {
        // Generate match plan with full context
        let plan = self.take_match_plan(config_index, length, terminating_char)?;

        // Policy is checked by the caller before deferred completion.

        // Static templates were rendered once while creating the plan. For a
        // command-backed match this field is unused until command completion.
        let template_text = plan.replacement_text.clone();

        // Consume buffer
        for _ in 0..length {
            self.buffer.pop_back();
        }
        self.deferred_matches.push(plan.matched_text.clone());

        Some(PendingExpansionResult {
            trigger: plan.trigger_config,
            matched_text: plan.matched_text,
            template_text,
            cursor_offset: plan.cursor_offset,
            reinsert_after: plan.terminating_char.filter(|_| self.reinsert_terminators),
            max_replacement_size: self.config.organization.max_replacement_size,
            config_index,
            generation: plan.generation,
            propagate_case: plan.propagate_case,
            cache_ms: plan.command.as_ref().map_or(0, |command| command.cache_ms),
            cached_output: plan.command.as_ref().and_then(|command| {
                (command.cache_ms > 0)
                    .then(|| self.command_cache[config_index].as_ref())
                    .flatten()
                    .filter(|entry| entry.expires_at > Instant::now())
                    .map(|entry| entry.value.clone())
            }),
            undoable: true,
            command: plan.command.as_ref().map(|c| (**c).clone()),
        })
    }

    /// Execute a command-backed expansion, using the short-lived cache when
    /// configured. Static templates are rendered while creating `MatchPlan`.
    fn render_expansion(&mut self, config_index: usize) -> Result<String, ()> {
        let expansion = &self.config.expansion[config_index];
        let Some(command) = &expansion.command else {
            return Err(());
        };
        if command.cache_ms > 0 {
            if let Some(entry) = self.command_cache[config_index].as_ref() {
                if entry.expires_at > Instant::now() {
                    return Ok(entry.value.clone());
                }
            }
        }
        let value = run_command(command).map_err(|_| ())?;
        if command.cache_ms > 0 {
            self.command_cache[config_index] = Some(CommandCacheEntry {
                expires_at: Instant::now() + Duration::from_millis(command.cache_ms),
                value: value.clone(),
            });
        }
        Ok(value)
    }

    /// Resets the matcher buffer to a known boundary. Always use this
    /// instead of `self.buffer.clear()` directly: it also clears
    /// `buffer_truncated`, since a fresh boundary means whatever preceded it
    /// is no longer relevant to word-boundary checks.
    fn clear_buffer(&mut self) {
        self.buffer.clear();
        self.buffer_truncated = false;
    }

    fn match_allowed(&self, config_index: usize, length: usize) -> bool {
        let expansion = &self.config.expansion[config_index];
        if !self.app_filter_allows(config_index, expansion) {
            return false;
        }
        if expansion.match_mode != MatchMode::WordBoundary {
            return true;
        }
        match self.buffer.iter().rev().nth(length) {
            Some(character) => !is_word_character(*character),
            // A `None` here is ambiguous unless we know nothing was ever
            // evicted: it means either "this is genuinely the start of
            // input" (allow) or "a preceding character existed but was
            // truncated out of the buffer" (unknown -- fail closed).
            None => !self.buffer_truncated,
        }
    }

    /// An expansion with an empty `app_filter` matches everywhere. A
    /// non-empty filter requires a known focused window whose app id contains
    /// one of the filter substrings (case-insensitive, preferred) or whose
    /// title contains one (as a fallback when app_id is unavailable); if
    /// window tracking is unavailable, this fails closed rather than
    /// matching unconditionally.
    ///
    /// App ID matching is preferred because it's more reliable than window
    /// titles, which can be user-editable or transient.
    fn app_filter_allows(&self, config_index: usize, expansion: &crate::ExpansionConfig) -> bool {
        if expansion.app_filter.is_empty() {
            return true;
        }
        let Some(window) = &self.normalized_window else {
            return false;
        };
        self.app_filters_lower[config_index].iter().any(|filter| {
            // If app_id is available, ONLY match against it (never fall back to title).
            // Rationale: app_id is set by the compositor and reliable; title is
            // user-editable and can be spoofed to match sensitive filters.
            if let Some(app_id) = window.app_id.as_deref() {
                app_id.contains(filter.as_str())
            } else if self.config.organization.disable_title_matching {
                // Policy: disable_title_matching means no title fallback.
                // Fail closed: don't match without app_id (per CLAUDE.md conventions).
                false
            } else {
                // App ID unavailable but title matching allowed: fall back to title
                window
                    .title
                    .as_deref()
                    .is_some_and(|title| title.contains(filter.as_str()))
            }
        })
    }

    /// Apply an expansion. Backends may perform the replacement atomically;
    /// simple backends use the safe erase-then-insert default.
    pub fn apply<I: TextInjector + ?Sized>(
        injector: &mut I,
        result: &ExpansionResult,
    ) -> Result<(), ExpansionError> {
        // A character that completed a delayed match has already reached the
        // application. Replace that character together with the trigger and
        // append it to the replacement in one backend operation. Use the text
        // actually typed for exact surrounding-text validation and
        // case-propagated triggers. Keeping both sides of this transaction
        // together is required for exclusive input-method backends too: they
        // forward the delimiter before the engine sees the corresponding
        // event.
        let mut erase = result.matched_text.clone();
        let mut insert = result.insert.clone();
        if let Some(character) = result.reinsert_after {
            erase.push(character);
            insert.push(character);
        }
        injector.replace(&erase, &insert)?;
        // Best-effort: a `{{cursor}}` marker's placement failing (or being
        // unsupported by this backend) does not mean the expansion itself
        // failed, since the replacement text above was already inserted.
        let trailing_offset = usize::from(result.reinsert_after.is_some());
        if let Some(offset) = result
            .cursor_offset
            .map(|offset| offset.saturating_add(trailing_offset))
            .filter(|offset| *offset > 0)
        {
            let _ = injector.move_cursor_left(offset);
        }
        Ok(())
    }
}

fn is_word_character(character: char) -> bool {
    character.is_alphanumeric() || character == '_'
}

/// Recases `text` (a rendered replacement) to match the casing pattern of
/// `typed` (the trigger as the user actually typed it), for expansions with
/// `propagate_case` enabled. A single capitalized letter or a capitalized
/// word yields a capitalized replacement; two or more uppercase letters
/// yield a fully uppercased replacement; anything else (typed as
/// configured, or mixed case) leaves the replacement unchanged.
fn apply_case_style(typed: &str, text: &str) -> String {
    let letters: Vec<char> = typed
        .chars()
        .filter(|character| character.is_alphabetic())
        .collect();
    match letters.as_slice() {
        [] => text.to_owned(),
        [single] if single.is_uppercase() => capitalize_first_letter(text),
        letters if letters.iter().all(|character| character.is_uppercase()) => text.to_uppercase(),
        [first, ..] if first.is_uppercase() => capitalize_first_letter(text),
        _ => text.to_owned(),
    }
}

/// Why a command-backed expansion's configured program did not produce
/// usable output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandError {
    /// The program could not be started at all (not found, not executable,
    /// permission denied, ...).
    SpawnFailed,
    /// The program did not exit within `command.timeout_ms` and was killed.
    Timeout,
    /// The process status could not be obtained after the program was started.
    WaitFailed(String),
    /// The program exited but reported failure.
    NonZeroExit(Option<i32>),
    /// Output exceeded the bounded size this engine will buffer.
    OutputTooLarge,
    /// Output exceeded an organization-configured replacement limit.
    PolicyOutputTooLarge { size: usize, limit: usize },
    /// Input changed or capture became disabled before a deferred match completed.
    StaleInput,
    /// Command execution was disabled by the active organization policy.
    PolicyBlocked,
    /// The bounded command queue is full.
    QueueFull,
    /// Asynchronous command workers could not be started or have stopped.
    WorkerUnavailable,
    /// Output was not valid UTF-8.
    InvalidUtf8,
    /// The output-reading thread did not report back in time (should not
    /// happen once the process itself has exited; treated as a distinct
    /// case rather than folded into `Timeout` since it points at a bug in
    /// the reader thread, not a slow command).
    OutputChannelLost,
}

impl std::fmt::Display for CommandError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CommandError::SpawnFailed => write!(f, "could not start the program"),
            CommandError::Timeout => write!(f, "timed out before it produced output"),
            CommandError::WaitFailed(error) => {
                write!(f, "failed while obtaining process status: {error}")
            }
            CommandError::NonZeroExit(Some(code)) => write!(f, "exited with status {code}"),
            CommandError::NonZeroExit(None) => write!(f, "was terminated by a signal"),
            CommandError::OutputTooLarge => write!(
                f,
                "produced more than {} bytes of output",
                MAX_COMMAND_OUTPUT_BYTES
            ),
            CommandError::PolicyOutputTooLarge { size, limit } => write!(
                f,
                "produced {size} bytes, exceeding the organization limit of {limit} bytes"
            ),
            CommandError::StaleInput => write!(f, "input changed before the expansion completed"),
            CommandError::PolicyBlocked => write!(f, "command execution is disabled by policy"),
            CommandError::QueueFull => write!(f, "command queue is full"),
            CommandError::WorkerUnavailable => write!(f, "command workers are unavailable"),
            CommandError::InvalidUtf8 => write!(f, "produced output that was not valid UTF-8"),
            CommandError::OutputChannelLost => write!(f, "output could not be read back"),
        }
    }
}

impl std::error::Error for CommandError {}

/// Runs a command-backed expansion's configured program to completion and
/// returns its trimmed stdout. Public so the GUI/CLI can invoke it directly
/// for an explicit, user-initiated "run once" preview -- callers must never
/// invoke this from a rendering/repaint loop, since it spawns a real process
/// with real side effects on every call.
pub fn run_command(command: &CommandConfig) -> Result<String, CommandError> {
    run_command_with_shutdown(command, None)
}

fn run_command_with_shutdown(
    command: &CommandConfig,
    shutdown: Option<&AtomicBool>,
) -> Result<String, CommandError> {
    let mut process = Command::new(&command.program);
    configure_command_environment(&mut process, command);
    process
        .args(&command.args)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null());
    configure_process_group(&mut process);
    let mut child = process.spawn().map_err(|_| CommandError::SpawnFailed)?;
    let stdout = child.stdout.take().ok_or(CommandError::SpawnFailed)?;

    #[cfg(unix)]
    {
        run_command_unix(child, stdout, command.timeout_ms, shutdown)
    }

    #[cfg(not(unix))]
    {
        run_command_fallback(child, stdout, command.timeout_ms, shutdown)
    }
}

#[cfg(not(unix))]
fn run_command_fallback(
    mut child: Child,
    stdout: ChildStdout,
    timeout_ms: u64,
    shutdown: Option<&AtomicBool>,
) -> Result<String, CommandError> {
    let (sender, receiver) = mpsc::sync_channel(1);
    thread::spawn(move || {
        let mut bytes = Vec::new();
        let result = stdout
            .take((MAX_COMMAND_OUTPUT_BYTES + 1) as u64)
            .read_to_end(&mut bytes)
            .map(|_| bytes);
        let _ = sender.send(result);
    });

    let deadline = Instant::now() + Duration::from_millis(timeout_ms);
    let status = loop {
        if shutdown.is_some_and(|flag| flag.load(Ordering::Acquire)) {
            kill_process_group(&child);
            let _ = child.wait();
            return Err(CommandError::StaleInput);
        }
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
            Ok(None) => {
                kill_process_group(&child);
                let _ = child.wait();
                return Err(CommandError::Timeout);
            }
            Err(error) => {
                kill_process_group(&child);
                let _ = child.wait();
                return Err(CommandError::WaitFailed(error.to_string()));
            }
        }
    };

    // Best-effort descendant cleanup for the platforms that use this fallback.
    kill_process_group(&child);

    if !status.success() {
        return Err(CommandError::NonZeroExit(status.code()));
    }
    let bytes = receiver
        .recv_timeout(Duration::from_millis(100))
        .map_err(|_| CommandError::OutputChannelLost)?
        .map_err(|_| CommandError::OutputChannelLost)?;
    if bytes.len() > MAX_COMMAND_OUTPUT_BYTES {
        return Err(CommandError::OutputTooLarge);
    }
    let output = String::from_utf8(bytes).map_err(|_| CommandError::InvalidUtf8)?;
    Ok(output.trim_end_matches(['\r', '\n']).to_owned())
}

#[cfg(unix)]
struct ChildGuard {
    child: Option<Child>,
}

#[cfg(unix)]
impl Drop for ChildGuard {
    fn drop(&mut self) {
        if let Some(ref mut child) = self.child {
            kill_process_group(child);
            let _ = child.wait();
        }
    }
}

#[cfg(unix)]
fn run_command_unix(
    child: Child,
    mut stdout: ChildStdout,
    timeout_ms: u64,
    shutdown: Option<&AtomicBool>,
) -> Result<String, CommandError> {
    let mut guard = ChildGuard { child: Some(child) };
    set_nonblocking_stdout(&stdout)?;
    let deadline = Instant::now() + Duration::from_millis(timeout_ms);
    let mut bytes = Vec::new();
    let mut stdout_eof = false;

    let status = loop {
        if shutdown.is_some_and(|flag| flag.load(Ordering::Acquire)) {
            return Err(CommandError::StaleInput);
        }
        if !stdout_eof {
            stdout_eof = read_available_stdout(&mut stdout, &mut bytes)?;
        }
        match guard.child.as_mut().unwrap().try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
            Ok(None) => {
                return Err(CommandError::Timeout);
            }
            Err(error) => {
                return Err(CommandError::WaitFailed(error.to_string()));
            }
        }
    };

    // Best-effort process-group cleanup handles ordinary descendants. It is
    // not a containment boundary: a deliberately trusted command can fork,
    // setsid(), and keep stdout open. Nonblocking reads below prevent that
    // case from pinning a WayExpand reader thread; service/cgroup containment
    // belongs in the planned Action Broker.
    if let Some(child) = &guard.child {
        kill_process_group(child);
    }

    let drain_deadline = Instant::now() + Duration::from_millis(100);
    while !stdout_eof && Instant::now() < drain_deadline {
        stdout_eof = read_available_stdout(&mut stdout, &mut bytes)?;
        if !stdout_eof {
            thread::sleep(Duration::from_millis(5));
        }
    }

    if !status.success() {
        return Err(CommandError::NonZeroExit(status.code()));
    }
    let output = String::from_utf8(bytes).map_err(|_| CommandError::InvalidUtf8)?;

    guard.child = None;
    Ok(output.trim_end_matches(['\r', '\n']).to_owned())
}

#[cfg(unix)]
fn set_nonblocking_stdout(stdout: &ChildStdout) -> Result<(), CommandError> {
    let fd = stdout.as_raw_fd();
    let flags = unsafe { libc::fcntl(fd, libc::F_GETFL) };
    if flags == -1 {
        return Err(CommandError::OutputChannelLost);
    }
    if unsafe { libc::fcntl(fd, libc::F_SETFL, flags | libc::O_NONBLOCK) } == -1 {
        return Err(CommandError::OutputChannelLost);
    }
    Ok(())
}

#[cfg(unix)]
fn read_available_stdout(
    stdout: &mut ChildStdout,
    bytes: &mut Vec<u8>,
) -> Result<bool, CommandError> {
    let mut buffer = [0_u8; 8192];
    loop {
        match stdout.read(&mut buffer) {
            Ok(0) => return Ok(true),
            Ok(count) => {
                bytes.extend_from_slice(&buffer[..count]);
                if bytes.len() > MAX_COMMAND_OUTPUT_BYTES {
                    return Err(CommandError::OutputTooLarge);
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => return Ok(false),
            Err(_) => return Err(CommandError::OutputChannelLost),
        }
    }
}

fn configure_command_environment(process: &mut Command, command: &CommandConfig) {
    if command.environment == CommandEnvironment::Inherit {
        return;
    }

    process.env_clear();
    for name in ["HOME", "USER", "LANG"] {
        if let Some(value) = std::env::var_os(name) {
            process.env(name, value);
        }
    }
    for name in &command.pass_env {
        if let Some(value) = std::env::var_os(name) {
            process.env(name, value);
        }
    }
    process.env("PATH", MINIMAL_COMMAND_PATH);
}

#[cfg(unix)]
fn configure_process_group(command: &mut Command) {
    unsafe {
        command.pre_exec(|| {
            if libc::setpgid(0, 0) == -1 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(())
        });
    }
}

#[cfg(not(unix))]
fn configure_process_group(_command: &mut Command) {}

#[cfg(unix)]
fn kill_process_group(child: &std::process::Child) {
    if let Ok(pid) = libc::pid_t::try_from(child.id()) {
        unsafe {
            libc::kill(-pid, libc::SIGKILL);
        }
    }
}

#[cfg(not(unix))]
fn kill_process_group(child: &mut std::process::Child) {
    let _ = child.kill();
}

#[cfg(test)]
#[path = "engine_tests.rs"]
mod tests;
